### ISSUE TITLE
0.6.0 broken :(

### ISSUE THREAD

**Issue by craigg75** [ocombe/ocLazyLoad#135]
Even though it fixed the Jasmine test runner issue, it broke my angular code. I reverted back to 0.5.2 for now which still works.

**Comment by ocombe** [comment]
Hmm I was thinking last night about something that might be a bad idea in my code, and maybe that's the reason it broke your app. I overrode the angular.module function but if you use it anywhere in your code it might try to reload your modules (it should do nothing in fact, but I need to check).
Do you have an error message ?

**Comment by craigg75** [comment]
Yeah I use angular.module in my app.js file. Well I get a couple of different errors. One says "[$injector:unpr] Unknown provider..." when it tries to load one my filters. Another says "[ng:areq] Argument '...' is not a function, got undefined" where ... is one of my controllers.

**Comment by ocombe** [comment]
Ok thanks, that's what I feared.
I'll fix this tomorrow :)

**Comment by ocombe** [comment]
Ok I just pushed a patch that should help, can you try the file from the src folder please ? https://github.com/ocombe/ocLazyLoad/blob/master/src/ocLazyLoad.js

**Comment by sochka** [comment]
I have "unknown provider" error too.

**Comment by sochka** [comment]
I also have "TypeError: Converting circular structure to JSON" - seems like this is coming from `ocLazyLoad` too.

**Comment by ocombe** [comment]
Ah this one (json) I can easily fix :)
But if you have a test case for the unknow provider one that would be perfect

**Comment by lookfirst** [comment]
Ok, after a lot of debugging, I think I know the issue with my app. I'm trying to test an angular controller that depends on ui-router in Karma. The issue is that I need to early inject `$ocLazyLoadProvider` somewhere in my code in order to get the internal `ocLazyLoad.init()` method to fire. It would be nice to not have to do that.

**Comment by craigg75** [comment]
For testing with jasmine or karma you really don't need ocLazyLoad in my opinion. I applaud Oliver's efforts here but just don't load ocLazyLoad when you are testing. Problem solved. I'd rather have O concentrate on keeping this module working with the latest angular builds. Just my 2 cents...

**Comment by lookfirst** [comment]
Sorry, but the problem isn't solved.

I don't have a choice here to not load ocLL. As I said, I'm testing an angular controller. The controller has a module dependency on an angular `module.config()` which sets up the router configuration. I'm using ocLL within the context of [ui-router-extras.future](http://christopherthielen.github.io/ui-router-extras/#/future) The router has a dependency on ocLL. This is just through the ES6 `import` chain, so there is no way to cut this out.

**Comment by craigg75** [comment]
Ouch.. bleeding edge. I understand.

**Comment by lookfirst** [comment]
@craigg75 Yes, I'm working my ass off on coming up with the 'perfect' seed of Gulp/SystemJS/Babel/Angular that has a good working example of a fully tested TodoMVC. The one thing that is getting in my way, in a big way right now, is ocLL. I'm on an unpublished branch right now, but the code is here: https://github.com/lookfirst/systemjs-seed

**Comment by ocombe** [comment]
Hmm what if the init function could be manually called to init ocLazyLoad whenever you want, would it fix your problem ?

**Comment by sochka** [comment]
@ocombe, I don't have a small failing example to show you... But here is the whole thing: 

https://github.com/kpi-wdc/wdc 

Whenever I change ocLazyLoad to 0.6.0 crazy errors immediately occur.

If you want to try build and run that - short instructions:

- ensure mongodb is installed
- clone it
- npm install
- npm start
- go to localhost:8080/app/default/data-representation

**Comment by ocombe** [comment]
A big example is good too, thanks, I'll take a look at it :)

**Comment by ocombe** [comment]
Ok, I fixed the json circular error, can you tell me where the "unknown provider" is so that I can fix this also ?

**Comment by ocombe** [comment]
@craigg75 do you have the code of the filter that triggers the "[$injector:unpr] Unknown provider..."  error ?

**Comment by sochka** [comment]
@ocombe I can't say exactly without reverting back to 0.6 (will do that later) - it was on a couple of the pages in <http://localhost:8080/app/default> . Could that happen because of runtime error with json resulting in non-proper handling of the module?

**Comment by lookfirst** [comment]
Ok, I have more details for you now. Things are still really broken, but now I have a way to show you more easily.

1. Grab this branch: https://github.com/lookfirst/systemjs-seed/tree/tests
1. npm install -g jspm gulp
1. npm install
1. gulp run
1. browse to http://localhost:9000

You should see the standard TodoMVC app.

Here is where the problems lie:

1. If you run `gulp test`, it says `Executed 0 of 3 ERROR`. This appears to be related to ocLL not loading the modules correctly. I know I stated above that injecting the provider should help, but I think I may have been wrong.
1. If you edit `jspm_packages/npm/oclazyload@0.6.0/dist/ocLazyLoad.min.js` and paste in the latest ocLL code from master, the TodoMVC app breaks. No errors, no stack traces, just silence in the browser.

You'll note that ocLL is loaded in `routing.js`.

**Comment by lookfirst** [comment]
@ocombe Not to pressure as I'm sure you're busy, but have you gotten a chance to take a look at things?

**Comment by ocombe** [comment]
No, I'll take a look at it tomorrow night, I don't have free time until then

**Comment by lookfirst** [comment]
@ocombe No worries. I just went through the commits and regarding problem 2 above is where things break for me... https://github.com/ocombe/ocLazyLoad/commit/35f7eb5be57f7753a20d7460c5a380f44e3ac175

**Comment by lookfirst** [comment]
@ocombe One more data point for you...

If I use this version of the file (which is the commit before 35f7eb5): https://github.com/ocombe/ocLazyLoad/blob/6634cbee6c5ce84363be84ae5529a61a633585b5/src/ocLazyLoad.js

AND

I comment out the entire `if` statement for adding unit test support... https://github.com/ocombe/ocLazyLoad/blob/6634cbee6c5ce84363be84ae5529a61a633585b5/src/ocLazyLoad.js#L985

THEN

Everything works great for both running and my unit tests.

Go figure.

**Comment by booleanbetrayal** [comment]
i've also experienced some issues with 0.6.0 that broke like this:

`application.js` - top level application. has shared *"moduleA"* concatenated into the amalgamation, however "moduleA" isn't explicitly required as a dependency for the top-level module or any of its sub-modules.

`optional.js` - has a dependency defined for *"moduleA"* and is loaded as needed by ocLazyLoad

as of 0.6.0, I now get unknown provider errors **unless I also declare *"moduleA*" a top-level dependency for the app (`application.js`).** I suspect concatenating *"moduleA"* into the `optional.js` amalgamation would fix this issue, but given that it's shared amongst other optional components, it is a bit problematic.

**Comment by ocombe** [comment]
Why don't you define __moduleA__ as a dependency of your top level module ?

**Comment by booleanbetrayal** [comment]
If I do that, it works in 0.6.0. However, it was working without explicitly doing that prior to updating to 0.6.0. It's fine if that's expected behavior, it's just behaving a bit differently than 0.5.2, which is why I'm pointing it out. 

It'd be nice to not have to define it though, since the top-level application doesn't really need to know anything about that module, and is only adding the src to the amalgamation as a convenient place for the optionally loaded amalgamations. ie - both `optional.js`, `optional2.js`, etc. would require it at some point.

**Comment by ocombe** [comment]
Are you using angular.bootstrap or starting your app with ng-app ?

**Comment by booleanbetrayal** [comment]
we're using `ng-app`. not sure if it affects anything, but the app is also configured / initialized via a `run` block.

**Comment by ocombe** [comment]
Nah, I was just reading the source code and found a potential bug with angular.bootstrap, but if that's not your case...

Anyway, yes 0.6.0 may have breaking changes with 0.5.x, that's why I updated the tag to 0.6.x.

With 0.5.x you had to define the names of the modules that you wanted to load, you don't need to do that with 0.6.x (that's why you can load multiple modules with the same file now), but the detection behavior is more strict:
- before the app starts, it keeps a list of all the modules declared using call angular.module
- when the app starts, it defines in the init function all those modules as "already loaded"
- once the app is loaded it doesn't listen to angular.module
- when you call $ocLazyLoad.load it starts listening to angular.module whenever a new file is injected into the DOM
- when all the files have been loaded it registers the new modules & components, and for each module it also registers its dependencies (if you loaded them before, they should already be available)

In your case the __moduleA__ is bundled with your application.js file, so it is available when the init function is called.

ocLazyLoad considers that your module has been defined before init and that angular has loaded it when you have started your application, that's why it doesn't try to register it.

When you new file is loaded, it will find __moduleA__ in the "already loaded" list of modules and won't try to register it again.

But the thing is that if you declare a module but don't define it as a dependency for your main application, then angular won't register the module (why execute something for nothing ?)...

The point is: you should declare the module as a dependency for your main app if you load it prior to init. Otherwise you should load it at the same time as your lazyloaded module. Put it in a separate file that can be loaded altogether with your other module if you want, this way it will be lazy loaded the first time you need it and the file won't be reloaded after (because it has already been downloaded).

**Comment by booleanbetrayal** [comment]
This all makes perfect sense, both philosophically and from an implementation perspective. Thanks for the concise breakdown, @ocombe . I was cheating with loading up a module's src in an amalgamation that didn't actually use it. In reality, I should probably be breaking these shared dependencies up into a bit more fine-grained definitions. I just wish my current pipeline was a bit more accommodating to refactors like that.  =]

**Comment by sochka** [comment]
It doesn't seem like my case is the same as @booleanbetrayal's. Theoretically detection should work fine if as described by @ocombe. On the other hand - I'm using `angular.bootstrap` if that matters.

**Comment by ocombe** [comment]
Yep angular.bootstrap is bugged I saw that this afternoon, I'm gonna fix it now :)

**Comment by ocombe** [comment]
Ok guys, I just released 0.6.1 and I hope that it fixes all of your problems. It fixes at least the ones that @sochka & @lookfirst helped me find with their projects (thanks a lot for that !).

If anyone still has an error, let me know (and please give me a test case!).

**Comment by sochka** [comment]
Huge thanks, will try that soon.

**Comment by lookfirst** [comment]
@ocombe Thanks!

In my seed project, `gulp test` works now, but `gulp run` (running the app in the browser) doesn't. I just get a blank screen with no errors. It feels like the module doesn't load.

To reproduce:

1. git clone https://github.com/lookfirst/systemjs-seed.git
1. Edit package.json and change the oclazyload dependency to yours: `"oclazyload": "npm:oclazyload@^0.6.1",`
1. Edit system.config.js and remove the oclazyload reference from the System.config(map:{}) line.
1. npm install -g jspm gulp
1. npm install
1. gulp run
1. browse to http://localhost:9000
1. You can also run `gulp test` to see that the tests pass now.

For what it is worth, this project is quickly becoming a good public test case for your project. :smile: :+1:

**Comment by ocombe** [comment]
Ok, got it, I know the commit that is the problem, let me find a way to fix that :)

**Comment by lookfirst** [comment]
:+1: Looking forward to the fix! Thanks so much for building this tool... I've done a bunch of research and nobody else has done it as well.

**Comment by ocombe** [comment]
Ok the problem is not really on my side, you're loading app/todo/todo.tpl.html & app/todo/todoModule.js after the app has been bootstrapped.

I just published 0.6.2 to take this case into account.

**Comment by lookfirst** [comment]
Right, because of the lazy loading (ui-router future stuff) in the router.js. It is a feature, not a bug. :lollipop:  =)

**Comment by lookfirst** [comment]
Perfect, it works! =)

**Comment by sochka** [comment]
Still doesn't work for me.

Error: [ng:areq] Argument 'HtmlWidgetController' is not a function, got undefined.

HtmlWidgetController is defined in a module, `$ocLazyLoad`-ed.

**Comment by leobudima** [comment]
0.6.2 doesn't work for me either...Thanks for the effort fixing it!

**Comment by lookfirst** [comment]
@sochka @leobudima: Please come up with a project and clear steps to reproduce the issue that @ocombe can use locally. Put yourselves in @ocombe's shoes... we can't expect him to guess at what the problem is. :smile:

**Comment by sochka** [comment]
@lookfirst my setup is posted above in the beginning of the thread.

**Comment by lookfirst** [comment]
@ocombe 

Ok, I have another broken use case... I'm now trying to integrate [ngReact](https://github.com/davidchang/ngReact/) into my seed app, which will be *very* cool once it starts working cause this is pretty much the best of both worlds in modern app development today.

I've [published a branch](https://github.com/lookfirst/systemjs-seed/tree/react) for you to try out. 

1. npm install -g jspm gulp
1. npm install
1. gulp run
1. browse to http://localhost:9000

If I remove the ['react'](https://github.com/lookfirst/systemjs-seed/blob/react/src/app/react/exampleApplication.jsx#L8) module declaration, then the html page loads. If I comment out the `export default reactExample` line, then I [see an error in ocLazyLoad](https://github.com/lookfirst/systemjs-seed/blob/react/src/app/react/exampleApplication.jsx#L13).

Looking at the loading chain, the react JS file doesn't load until *after* my exampleApplication.js file does, even though I've declared it as an import at the top of the file. It feels like that is at least part of the issue.

**Comment by ocombe** [comment]
@sochka well it works fine for me with v0.6.2 (I can go to http://localhost:8080/app/default/ and see that it lazy loads the file `widgets/htmlwidget/widget.js` that contains the `HtmlWidgetController` that you're talking about), are you sure that you upgraded and rebuilt your app?
If you still find a bug, please tell me where it is in your app (in details, because I don't speak Ukrainian and it's a bit hard to navigate when you don't know what the links mean :D).

**Comment by ocombe** [comment]
@lookfirst I fixed the bug of the `TypeError: Cannot read property 'files' of null`, thanks.
You should add a rejected callback to $ocLazyLoad.load like this:
```js
$ocLazyLoad.load(newModule).then(function() {
  def.resolve();
}, function(err) {
  throw err;
});
```

It's easier to see the errors if you throw them :)

The error in this case being that you forgot to import the ngReact module. Add `
import ngReact from 'ngreact';` and it will work just fine (and you wouldn't have had the error that I just fixed).

By the way, I'm impressed by your code, how did you managed to make SystemJS use ocLazyLoad for imports?

**Comment by ocombe** [comment]
Oh yeah it's based on the code of @amcdnl, it calls System.import when a route is loaded, clever :)

**Comment by sochka** [comment]
@ocombe sorry, I found the reason - you have to switch to `develop` branch first and then yes - browse http://localhost:8080/app/default

**Comment by sochka** [comment]
The differency may be because in `develop` branch I also switched from requirejs to SystemJS. (I use `window.require = System.amdRequire` as $ocLazyLoad loader.)

**Comment by lookfirst** [comment]
Oh, I didn't know about the error handler... can you please add that to the docs (or I will submit a PR later today). Sure, it is just the promise error, but it is helpful for debugging for sure.

Yes, I took two main bits from @amcdnl's codebase... the [routing.js](https://github.com/lookfirst/systemjs-seed/blob/master/src/common/utils/routing.js) and the even cooler [route bundler](https://github.com/Swimlane/systemjs-route-bundler) which will bundle based on route!

Now that I've integrated ngReact, I'm super excited by the possibility of having the choice of both angular and react in the same project. It is going to make things really interesting, having DI for react projects is a killer feature.

**Comment by amcdnl** [comment]
@ocombe so I guess since 1.5 will have lazy-loading there is no need for ocLazyLoad in the near future :(

**Comment by ocombe** [comment]
See https://github.com/ocombe/ocLazyLoad/issues/138 for a response to this question @amcdnl

**Comment by sochka** [comment]
Hi, for me the issue is still present. I'm staying on 0.5.2, upgrading to 1.0.1 gives this error: `Error: no file to load has been found, if you're trying to load an existing module you should use the 'inject' method instead of 'load'.`

**Comment by ocombe** [comment]
@sochka this error happens when you try to load a module by name but haven't configured the provider with this module. Before 1.0.1 you would just get no error but nothing would have been loaded.

**Comment by sochka** [comment]
Do I have to know the module name before I load it?

**Comment by ocombe** [comment]
No, you should call `$ocLazyLoad.load` with urls, not module names (unless you registered them in the config).
How do you call it ?

**Comment by sochka** [comment]
Oh, I see. Until now I was doing 

```
// start loop
          widgetControllers.push({
            name: `app.widgets.${widget}`,
            files: [appUrls.widgetJSModule(widget)]
          });
// end loop
$ocLazyLoad.load(widgetControllers)
```

Not I replaced loop body with
```
          widgetControllers.push({
            name: `app.widgets.${widget}`,
            files: [appUrls.widgetJS(widget)] // this is an url for widget's javascript
          });
```

But I'm getting a bunch of random js errors not present when using 0.5.2
```
Uncaught TypeError: Cannot read property '__useDefault' of undefinedrequire @ system.src.js:2502(anonymous function) @ widget.js:1
angular.js:12221 TypeError: angular.element(...).width is not a function
    at app.js:461
    at Object.$watchCollectionAction [as fn] (angular.js:15421)
    at Scope.$get.Scope.$digest (angular.js:15556)
    at angular.js:15758
    at completeOutstandingRequest (angular.js:5370)
    at angular.js:5642(anonymous function) @ angular.js:12221$get @ angular.js:9055$get.Scope.$digest @ angular.js:15574(anonymous function) @ angular.js:15758completeOutstandingRequest @ angular.js:5370(anonymous function) @ angular.js:5642
angular.js:12221 Error: [ng:areq] Argument 'HtmlWidgetController' is not a function, got undefined
http://errors.angularjs.org/1.4.0/ng/areq?p0=HtmlWidgetController&p1=not%20aNaNunction%2C%20got%20undefined
    at REGEX_STRING_REGEXP (http://localhost:8080/components/angular/angular.js:68:12)
    at assertArg (http://localhost:8080/components/angular/angular.js:1765:11)
    at assertArgFn (http://localhost:8080/components/angular/angular.js:1775:3)
    at http://localhost:8080/components/angular/angular.js:8921:9
    at setupControllers (http://localhost:8080/components/angular/angular.js:8003:36)
    at nodeLinkFn (http://localhost:8080/components/angular/angular.js:8043:32)
    at compositeLinkFn (http://localhost:8080/components/angular/angular.js:7514:13)
    at publicLinkFn (http://localhost:8080/components/angular/angular.js:7388:30)
    at ngIncludeFillContentDirective.link (http://localhost:8080/components/angular/angular.js:23926:38)
    at invokeLinkFn (http://localhost:8080/components/angular/angular.js:8604:9)
```

**Comment by ocombe** [comment]
First of all, you don't need to give the name of the module anymore, the url of the file is enough (magic inside!), so you can just do:

```
widgetControllers.push(appUrls.widgetJS(widget));
```

As for the errors I'm not sure, isn't it because you upgraded your app to angular 1.4 at the same time and these modules aren't compatible ?
I don't see ocLazyLoad in the stacktrace, so I'm not sure this is really the cause. I would need a plunkr to investigate.

**Comment by sochka** [comment]
@ocombe , checked angular 1.3 - same error. I created a heroku app for you to try: https://wdc-app-testing.herokuapp.com/app/sustainable-development/
