### ISSUE TITLE
Reloading libs loaded using {'serie': true} "consumes" files list 

### ISSUE THREAD

**Issue by JohannesRudolph** [ocombe/ocLazyLoad#160]
Check this plnkr: http://plnkr.co/edit/oRj4EggNZLgfOQxASawi?p=preview

Look at the console output when navigating via "go to other" and "go to index". After the first navigation, you will notice that module.files has become empty. It appears that ocLazyLoad when used with the serie:true config option consumes the file list instead of cloning it for internal use. 

This has created issues for us with ocLazyLoad trying to reload empty/undefined files.

**Comment by ocombe** [comment]
Oh you're right, thanks for the debug!

**Comment by JohannesRudolph** [comment]
Happy to help! It's a great library!

**Comment by ocombe** [comment]
Fixed! :)

**Comment by JohannesRudolph** [comment]
Thanks, will check it out :+1:

**Comment by ocombe** [comment]
There is no new release yet since I'll be making more commits tonight

**Comment by 4ants** [comment]
This bug is still present. I get 'File type could not be determined. undefined' when accessing UI state that is previously loaded.

**Comment by ocombe** [comment]
Are you sure it's the same problem ?

**Comment by 4ants** [comment]
When I load UI router state first time, everything is ok, but when I access it second time it throws 'File type could not be determined. undefined'. This is probably because all required files are loaded and ocLazyLoad tries to load empty list. Everything works, it just throws error in console (when debug: true) is set.

**Comment by yogiswar1987** [comment]
How is this closed??
